# Generated by Django 5.1.6 on 2025-02-20 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weathersearch',
            name='user',
        ),
    ]
